#!/usr/bin/env node
/* 把 data/offers-*.json 合并成 site/data/offers.js */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DATA = path.join(ROOT, 'data');
const OUT = path.join(ROOT, 'site', 'data', 'offers.js');

const BADGES = ['no-card', 'no-expiry', 'daily-refresh', 'one-time'];
const CATS = ['llm', 'gpu', 'embedding', 'speech', 'image', 'agent', 'hosting'];

function readJson(f) {
  try {
    return JSON.parse(fs.readFileSync(f, 'utf8'));
  } catch (e) {
    console.error('  ! 解析失败，跳过:', path.basename(f), e.message);
    return [];
  }
}

const files = fs.readdirSync(DATA)
  .filter(f => /^offers-.*\.json$/i.test(f))
  .sort();

if (!files.length) { console.error('没有找到任何 offers-*.json'); process.exit(1); }

let all = [];
const stats = { official: 0, secondary: 0, unknown: 0 };

for (const f of files) {
  const rows = readJson(path.join(DATA, f));
  if (!Array.isArray(rows)) continue;
  for (const r of rows) {
    if (!r.name) continue;
    if (BADGES.indexOf(r.badge) === -1) r.badge = 'one-time';
    if (!r.card_required) r.card_required = 'unknown';
    r.category = (r.category || []).filter(c => CATS.indexOf(c) > -1);
    if (!r.category.length) r.category = ['llm'];
    stats[r.confidence] = (stats[r.confidence] || 0) + 1;
    all.push(r);
  }
  console.log(`  ${f}: ${rows.length} 条`);
}

// 去重（按 id）
const seen = new Set();
all = all.filter(r => {
  if (seen.has(r.id)) return false;
  seen.add(r.id);
  return true;
});

all.sort((a, b) => (a.featured || 999) - (b.featured || 999));

const banner = '/* ============================================================\n' +
  '   sneaktoken.com — free tier data\n' +
  '   Generated by tools/merge-offers.js — do not edit by hand.\n' +
  '   Edit data/offers-*.json instead, then re-run the merge.\n' +
  '   Last generated: ' + new Date().toISOString().slice(0, 10) + '\n' +
  '   ============================================================ */\n';

fs.writeFileSync(OUT, banner + 'window.OFFERS = ' + JSON.stringify(all, null, 2) + ';\n', 'utf8');

console.log(`\n合并完成 → site/data/offers.js`);
console.log(`  共 ${all.length} 条（官方确认 ${stats.official || 0} · 二手 ${stats.secondary || 0} · 未确认 ${stats.unknown || 0}）`);
